#!/usr/bin/env python
# -*- coding: utf-8 -*-

# Import from the standard library
from os.path import split
import argparse
import pandas as pd

# Import from projectaishu
import projectaishu
from projectaishu.lib import clean_data, try_me


if __name__ == '__main__':
    try_me()
